# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sleeplessy's Messy Bedroom
email: csscss3@hotmail.com

#write html inside the double quotes to display in jumbotron
description: "<h3>Life for CODE.Life for OTAKU.</h3><h1>Sleeplessy | Tsao Shisong</h1>Still Struggle."



baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sleeplessy.github.io" # the base hostname & protocol for your site
twitter_username: Sleeplessy_C
github_username:  Sleeplessy

# Build settings
markdown: kramdown

# Plugins settings:
gems:
  - jemoji